NCIOCPL/cdr-server

Filters/CDR0000000134.xml

Modifying Term filter to suppress "clinical trials" link if C-code has not been made public yet.

Removing links to unpublished C-codes. OCECDR-4322

---

Schemas/CitationSchema.xml

Track changes in NLM's DTD (OCECDR-4337)

---

Filters/CDR0000335424.xml

Creating new pull request since I closed the original one accidentally.

Cdr4423 qcpv

---

Filters/CDR0000315588.xml

Filter change for Unusual Cancer summary.

Removing Special Consideration section. OCECDR-4409

---

Schemas/CitationSchema.xml

This is about to land on PROD.

Allow inline markup in ArticleTitle (OCECDR-4432)

---

Filters/CDR0000339576.xml
Filters/CDR0000380958.xml

Modify images to be displayed at center.

Modify display of images in QC reports. OCECDR-4296

---

api/web.config

Deployed to production Monday 2018-03-26.

Allow uploading of large media files (OCECDR-4444)

---

Filters/CDR0000339576.xml

Restoring code to remove the Special Consideration section from the QC reports.

Restoring Special Consideration section

---

Filters/CDR0000000079.xml
Filters/CDR0000315892.xml
Filters/CDR0000321373.xml
Filters/CDR0000335169.xml
Filters/CDR0000335417.xml
Filters/CDR0000335418.xml
Filters/CDR0000339576.xml

It appears that the "Special Consideration" section code will be removed with this merge again (CDR0000339576.xml).  This had been restored to the master branch with [bbfdf20] and my master branch had been updated after that commit.

Cdr4445 citsort

---

Filters/CDR0000339576.xml

I'm trying to see if I can reproduce the git behavior you're seeing, @venglisch.

Re-apply OCECDR-4281 patch (3rd time's a charm)

---

Filters/CDR0000000154.xml
Filters/CDR0000335169.xml

Fix to display PlaceHolder and Glossary in Misc. Doc QC report.
Hoping Houdini will leave us alone this time.

Cdr4390 miscdoc

---

Filters/CDR0000257553.xml
Filters/CDR0000339576.xml
Filters/CDR0000613261.xml

Misc. GTN/GTC QC report changes, i.e. adding VideoLink.

Cdr4459 gtcall

---

Filters/CDR0000257553.xml
Filters/CDR0000339576.xml
Filters/CDR0000613261.xml

This is the last change for the GTC QC reports including some of the modifications we talked about earlier.

Cdr4460 gtc

---

Schemas/CdrCommonBase.xml

Schema change promoted to PROD.

Adding EmbeddedVideo element to ListItem. OCECDR-4557

---

Filters/CDR0000486311.xml

The filter has been copied to PROD.

Adding markup to some elements. Fixing date display. OCECDR-4525

---

Filters/CDR0000505580.xml

The filter has been updated on PROD.

OCECDR-4535: Allow multiple DrugReferenceLinks

---

Filters/CDR0000000096.xml
Filters/CDR0000000099.xml

I just noticed that I never merged this branch into master.  We had restored these two filters that were removed as part of Ising back in October.

Restoring QC report for Person and Orgs. OCECDR-4513

---

Filters/CDR0000000050.xml
Filters/CDR0000000100.xml
Filters/CDR0000315593.xml
Filters/CDR0000315594.xml
Filters/CDR0000423177.xml

- Adding org/person filters to github that had already been restored to the CDR
- Removing borders from table cells in Org QC report
- Fixing QC report header (adding timestamp)

Cdr4607 orgqc

---

Schemas/CitationSchema.xml

Landed on production 2019-01-07.

[OCECDR-4556] Fix schema validation error

---

Filters/CDR0000335166.xml
Filters/CDR0000380957.xml

This is a summary QC filter change that went to PROD.  I'm hoping that @blairlearn  can approve the PR since @bkline is out this week.

Cdr4534 markup comments

---

Filters/CDR0000616048.xml

Again, I'm adding @blairlearn since @bkline is out this week - at least in theory. :-) 
Simple punctuation change for Spanish list of synonyms.

Modify Spanish punctuation. OCECDR-4626

---

Filters/CDR0000335169.xml
Filters/CDR0000486311.xml
Filters/CDR0000486313.xml

Added ability to display video in DIS documents.

Display embedded video in QC report. OCECDR-4615

---

Filters/CDR0000712005.xml

One change to specify the version of the denormalized document plus a bunch of trailing white space fixes.

Require publishable module for denormalization. OCECDR-4675

---

Filters/CDR0000339576.xml

The filter change to remove "DocVersion=-1" has been copied to PROD.

Fixing summary links in summries. OCECDR-4757

---

Filters/CDR0000712005.xml

Filter changes tested and pushed to PROD.

Setting default to isQC=N. OCECDR-4756

---

Filters/CDR0000257553.xml

This QC filter change is now on PROD.
Sorry, there is a bunch of white space noise.

Removing image and video of RelatedGlossary from displaying. OCECDR-4792

---

Filters/CDR0000797103.xml

Filter changes for summary image links are now on PROD.

Cdr4798 media server

---

Filters/CDR0000409593.xml

Filter changes to correct the missing glossary definitions for Spanish HP summary QC reports.

Cdr4728 gloss table

---

Filters/CDR0000616048.xml

This filter change has been copied to PROD.

Cdr4808 - Modify Spanish Conjunction

---

Filters/CDR0000800354.xml
Filters/CDR0000800355.xml

The latest versions of these two filters have been restored on production.

Glossary loader

---

Filters/CDR0000339576.xml
Filters/CDR0000380956.xml
Filters/CDR0000410709.xml
Filters/CDR0000434822.xml
Filters/CDR0000800878.xml

Modifications to the display of images and videos in QC reports.
The filters modified for this ticket have been copied to PROD.

(OCECDR-4674) Image/Video Caption Markup

---

Filters/CDR0000505580.xml

Minor change to update URL from DIS document to drug dictionary term.

(OCECDR-4851) Modify URL from DIS

---

Filters/CDR0000800355.xml

Landed on PROD 2020-07-16.
Fixes OCECDR-4853.

Fix missing genetics images

---

Filters/CDR0000434822.xml

The modified filter has been copied to PROD.

Correcting missing space between Citation and GeneName

---

Filters/CDR0000271370.xml
Filters/CDR0000486311.xml
Filters/CDR0000486313.xml
Filters/CDR0000505580.xml
Filters/CDR0000797104.xml
Filters/CDR0000802090.xml

Modifying denormalization of video content; creating new module for Drupal CMS filters to share.

(OCECDR-4614) Allow EmbeddedVideo within Section element for DIS

---

Filters/CDR0000335424.xml

Trivial error message modification pushed to PROD.

(OCECDR-4856) Modify error message for empty SummaryRef element

---

Schemas/Drug.xml

I forgot to submit this PR after moving the changes to PROD.
Adding a value to a LOV.

(OCECDR-4929) Add FDAApproved value

---

Filters/CDR0000335424.xml

Added error message for summaries without Spanish translation for LOE; removed unused code.
Changes are now on PROD.

(OCECDR-4938) Genetics summary - adding error message

---

Filters/CDR0000800355.xml

Single line filter change copied to production.

(OCECDR-4945) Include domain name to PROD for LOE links

---

Filters/CDR0000594604.xml

Filter change has been copied to STAGE and PROD.

(OCECDR-4955) Don't add ellipsis to shorter titles

---

Filters/CDR0000699063.xml

Minor changes to sync up the Quick-and-Dirty (QD) report with the regular QC reports since those diverged a bit over time.

(OCECDR-4942) Sync up summary QC and QD-QC reports

---

Filters/CDR0000616048.xml

Excluding term definitions with 'Rejected' status (plus some additional cleanup).

(OCECDR-4950) Fix Spanish Genetics dictionary terms

---

Filters/CDR0000335424.xml
Filters/CDR0000409593.xml
Filters/CDR0000434822.xml
Filters/CDR0000699063.xml

Also updated QC QD report including some additional clean-up; always a little bit of clean-up.

OCECDR-4938b Display proper denormalization error message

---

Filters/CDR0000434822.xml

The filter changes have been pushed to production.

Cdr4990 Suppress Display of Intervention from SectMetaData

---

Filters/CDR0000616048.xml

These filter changes to correct Spanish conjunction have been copied to production.

Cdr5015 synonym es

---

Filters/CDR0000000157.xml
Filters/CDR0000335424.xml

Minor changes to allow proper PlaceHolder substitutions for new Spanish genetics summaries.
It also includes a bunch of white space changes.

Cdr5074 genetics es

---

Filters/CDR0000000157.xml
Filters/CDR0000335166.xml
Filters/CDR0000335169.xml
Filters/CDR0000339576.xml
Filters/CDR0000434822.xml
Filters/CDR0000712005.xml

Changes for module display within QC reports plus lots of "noise" (white space changes).

Oppenheimer

---

Filters/CDR0000797103.xml

The filter change has been copied to production.

(OCECDR-5098) Fix summary fragment link on Cancer.gov/PublishPreview

---

Schemas/GlossaryTermConcept.xml

Pretty straightforward, I think. Landed on production Valentine's Day of 2022.

Add SourceKey attribute (OCECDR-5076)

---

Filters/CDR0000315588.xml
Filters/CDR0000616048.xml

These filters have been copied to production and ran successfully.

(OCECDR-5090) Add website description to related external info

---

Database/Loader/trials--overrides.txt

Part of the Oppenheimer mini-release, deployed to production Thursday 2022-09-08.

Remove obsolete rules

---

Filters/CDR0000797104.xml

Filter change to markup subscript/superscript for DIS documents copied to PROD.

(OCECDR-5157) Fix sub-, superscript markup for DIS

---

Filters/CDR0000339576.xml

Changes fix the display of proposed list items on the bold/underline reports.

(OCECDR-5151) Fix display of proposed list item in BU QC report

---

Filters/CDR0000000157.xml

Filter change has been promoted to PROD.

(OCECDR-5179) Remove template to process PDQ-DB PlaceHolder element

---

Filters/CDR0000609947.xml
Schemas/CdrCommonBase.xml
Schemas/SummarySchema.xml

Deployed to production 2023-06-06.

Browser title

---

Filters/CDR0000000154.xml

Placeholder display for citations modified to sequence numbers.

(OCECDR-5207) Replace placeholders with sequence numbers for citations

---

Filters/CDR0000000134.xml
Filters/CDR0000505580.xml

The filter changes to adjust the link to the clinical trials page have been copied to PROD.

(OCECDR-5275) Update clinical trials search URL

---

Filters/CDR0000000157.xml

Filter changes have been copied to STAGE and PROD.

(OCECDR-5296) Modify hard coded Spanish section title

---

Filters/CDR0000000160.xml

Updated the fixed filter changes to PROD.

(OCECDR-5330) Fix Summaries TOC Report

---

Database/pub_proc_status_completed.py
Database/tables.sql

Part of the minor patch release Sanger, deployed 2025-01-16.

Add index to pub_proc table (OCECDR-5363)
